import React from 'react'
import DocumentTitle from 'react-document-title'
import { Link } from 'react-router-dom'
import { scrollTop } from '../AllFunctions'
import Header from '../Bangla/Header'
import Footer from '../Bangla/Footer'


export default function PrivacyPolicy() {
    return (
        <div className='page-bangla'>
            <Header />
            <main>
                <div className="container">
                    <div className="TopHomeSection"></div>
                    <DocumentTitle title='Daily Bangladesh :: ডেইলি বাংলাদেশ - Privacy Policy' />
                    <h2 class="mvp-feat1-pop-head DTitle En"><Link to="/privacy-policy" onClick={scrollTop}><span class="mvp-feat1-pop-head">Privacy Policy</span></Link></h2>

                    <div className='row mt-5 policy-details'>
                        <div className='col-lg-12'>
                            <p>Daily Bangladesh is committed to protecting your personal information when you are using any of the websites or applications from Daily Bangladesh. This Privacy Policy relates to using any personal information that it collects from visitors/readers via the following, among other, services:</p>
                            <div className='policy-list'>
                                <ul>
                                    <li>any Daily Bangladesh website that links to this privacy policy;</li>
                                    <li>social media or official Daily Bangladesh content on other websites;</li>
                                </ul>
                            </div>
                            <div className='mt-3'>
                                <p>In all the above services, the <Link className='links' onClick={scrollTop} to="/privacy-policy">"Privacy Policy"</Link> shall apply only when the application, website, or contents therein are truly & genuinely generated by Daily Bangladesh. Provided that, no application, website, or contents therein are generated or presented at any false or fake website, page, or group in the name (or with false logo) of Daily Bangladesh, won't get this protection.</p>
                                <p>Daily Bangladesh collects or receives information about its users for many purposes; for instance, to provide services designed to serve the user, to monitor and improve the services offerings, for marketing or targeting advertisement, etc. Such information may include your name, address, phone number, email address, age, social network account, etc. ("the information").</p>
                                <p>There may be other privacy policies that apply to certain services provided by Daily Bangladesh. Visitors are requested to read these while registering or subscribing to these services on these sites. Daily Bangladesh respects the privacy of its visitors/readers and makes use of its best effort to ensure that the information collected is used for the limited purpose for which it was received.</p>
                            </div>
                            {/*Special Precaution  */}
                            <div className='mt-3'>
                                <h2 class="heading">Special Precaution</h2>
                                <div className='mt-3'>
                                    <p>There lies, in the name of Daily Bangladesh, multiple fake websites and Facebook pages and unauthorized/ unwanted Facebook groups online. Daily Bangladesh shall hold no responsibility for any content generated, published, or shared in those fake websites, unauthorized pages & groups in social media.</p>
                                </div>
                            </div>
                            {/* How Daily Bangladesh collects the information */}
                            <div className='mt-3'>
                                <h2 class="heading">How Daily Bangladesh collects the information</h2>
                                <div className='mt-3'>
                                    <p>Daily Bangladesh collects the information on a user upon the user's access to the Daily Bangladesh website - (i) by registering to the site or Apps, (ii) subscribing to the newsletter, (iii) responding to a survey, or participating in a competition, (iv) logging-in to a site or page, etc.</p>
                                </div>
                            </div>
                            {/* Disclosure of Information Collected */}
                            <div className='mt-3'>
                                <h2 class="heading">Disclosure of Information Collected</h2>
                                <div className='mt-3'>
                                    <p>Daily Bangladesh does not sell, trade, or otherwise provide personally identifiable information to any other parties except for those that assist Daily Bangladesh in operating its website, conducting the business, and serving the users. It may share visitor's/readers ' personal information internally to understand the user base, promote the number of users and increase user engagement. In the event that Daily Bangladesh desires to use personal information in a different way than that described above, it shall seek the consent of the individual. Daily Bangladesh may release personally identifiable information if it is required to comply with the laws of Bangladesh. Not with standing anything contained in this Privacy Policy, Daily Bangladesh may disclose or share information collected including personal information to service providers, affiliate companies, consultants, advisors, or Partners that it has engaged to perform business-related functions on its behalf. Daily Bangladesh may also share the information in response to the legal process, or protect its interest in any forum. The information may be used for investigating or preventing potentially illegal activities, or situations involving potential threats to any person, us, or the services, or violations of our policies, the law, or our <Link to="/terms-conditions" onClick={scrollTop}>"Terms of Use"</Link> as well as to verify or enforce compliance with the policies governing our Services. The information may as well be shared to offer market products or services to the visitors/readers. However, in all these events or any other event when personal information is shared or disclosed, Daily Bangladesh shall use its best endeavors to control the share or disclosure and shall only share to such extent as it is required to meet the purpose.</p>
                                </div>
                            </div>
                            {/* Data Retention */}
                            <div className='mt-3'>
                                <h2 class="heading">Data Retention</h2>
                                <div className='mt-3'>
                                    <p>We shall hold visitor's/readers' personal information if your account exists with Daily Bangladesh. Notwithstanding, Daily Bangladesh may retain data for a further period as per its own internal data retention policy. Visitor's/reader's personal information shall be deleted upon expiry of your Daily Bangladesh account. Please note that there may be events when the erasing/deleting of information may take more time than usual, and Daily Bangladesh shall not hold any responsibility for such events.</p>
                                </div>
                            </div>
                            {/* Advertisement */}
                            <div className='mt-3'>
                                <h2 class="heading">Advertisement</h2>
                                <div className='mt-3'>
                                    <p>The advertisements included in the Daily Bangladesh website and Apps, are by third-party companies & ad networks through independent ad tags, which may collect information about users for which Daily Bangladesh shall bear no responsibility that may arise as a result of collecting and/or sharing the information with any other party. Daily Bangladesh shall not accept any liability that may arise as a result of any content of any advertisement that may appear on the Daily Bangladesh website.</p>
                                </div>
                            </div>
                            {/* Third-Party Advertisements and links */}
                            <div className='mt-3'>
                                <h2 class="heading">Third-Party Advertisements and links</h2>
                                <div className='mt-3'>
                                    <p>At the discretion of Daily Bangladesh, the website or application may display or allow advertisements of third-party services or products. These third-party sites may have separate and independent privacy policies. Daily Bangladesh accepts no responsibility or liability for the content of advertising material, including, without limitation, any error, omission, or inaccuracy therein. Daily Bangladesh does not hold any responsibility for information leakage due to the visitor/reader accessing a separate link, application, or website, whether through a link in the website or contents of Daily Bangladesh.</p>
                                </div>
                            </div>
                            {/* Use of Cookies */}
                            <div className='mt-3'>
                                <h2 class="heading">Use of Cookies</h2>
                                <div className='mt-3'>
                                    <p>Daily Bangladesh does not collect any user data based on cookies, nor does it store any sort of user information that may be personal to the user. If a third party associated with the Daily Bangladesh website collects user cookies upon your visit to the Daily Bangladesh website, Daily Bangladesh does not control the use of these cookies therefore you should check the relevant third-party website.</p>
                                </div>
                            </div>
                            {/* Demographic and purchase information: */}
                            <div className='mt-3'>
                                <h2 class="heading">Demographic and purchase information</h2>
                                <div className='mt-3'>
                                    <p>We may reference other sources of demographic and other information to provide you with more targeted communications and promotions. We use Google Analytics, among others, to track user behavior on our website. You can opt-out of Google Analytics for Display Advertising and customize Google Display Network ads using the Ads Settings options provided by Google.</p>
                                </div>
                            </div>
                            {/* Communication by Daily Bangladesh */}
                            <div className='mt-3'>
                                <h2 class="heading">Communication by Daily Bangladesh</h2>
                                <div className='mt-3'>
                                    <p>From time to time, Daily Bangladesh may contact its users via e-mail, phone, or SMS for invitation for participation in campaigns/competitions organized by Daily Bangladesh, feedback, survey, etc. based on the information it has received from the users.</p>
                                </div>
                            </div>
                            {/* Accessing the website from outside Bangladesh */}
                            <div className='mt-3'>
                                <h2 class="heading">Accessing the website from outside Bangladesh</h2>
                                <div className='mt-3'>
                                    <p>All personal information submitted by users outside Bangladesh will be processed in accordance with these <Link className='links' onClick={scrollTop} to="/terms-conditions">"Terms of Use"</Link> and <Link className='links' onClick={scrollTop} to="/privacy-policy">"Privacy Policy"</Link>.</p>
                                </div>
                            </div>
                            {/* Governing Law */}
                            <div className='mt-3'>
                                <h2 class="heading">Governing Law</h2>
                                <div className='mt-3'>
                                    <p>The laws that govern the <Link to='/privacy-policy' className='links' onClick={scrollTop}>"Privacy Policy"</Link> of Daily Bangladesh and its relationship with the user is the laws of Bangladesh and any dispute regarding the use, retention, disclosure, leakage, or dissemination of the information or date can only be raised before the courts of Bangladesh which shall have exclusive jurisdiction on this matter. The entire <Link to='/privacy-policy' className='links' onClick={scrollTop}>"Privacy Policy"</Link> shall apply to all who enter the website, receive service, or use an application from Daily Bangladesh regardless of their nationality, location, residence, or place of business.</p>
                                </div>
                            </div>
                            {/* Modification of Privacy Policy */}
                            <div className='mt-3'>
                                <h2 class="heading">Modification of Privacy Policy</h2>
                                <div className='mt-3'>
                                    <p>Daily Bangladesh reserves the right to amend, modify, alter, or omit any terms in the  <Link to="/privacy-policy" className='links' onClick={scrollTop}>"Privacy Policy"</Link> at any time but the changed policy shall be immediately uploaded or updated on the website. By continuing to use our services after any changes are made, you accept those changes and will be bound by them. We encourage you to periodically check back and review this policy so that visitors/readers will always know what information we collect, how we use it, and with whom we share it.</p>
                                </div>
                            </div>
                            {/* Opt-out */}
                            <div className='mt-3'>
                                <h2 class="heading">Opt-out</h2>
                                <div className='mt-3'>
                                    <p>If at any time, the users prefer not to receive emails containing marketing information from us, then the user can simply follow the unsubscribe options at the bottom of each email. If the users no longer wish to have a registered account, the user may terminate the account by sending an email to <a href='mailto: newsroom@daily-bangladesh.com' className='mail-link'>newsroom@daily-bangladesh.com</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    )
}
